### ISSUE TITLE
Rapid connect and writes cause error

### ISSUE THREAD

**Issue by chazomaticus** [myndzi/syslog2#3] opened 2015-02-05 02:53 UTC
With this code:
```js
var Syslog = require('syslog2');
var log = Syslog.create({
    connection: {
        type: 'udp',
        host: '127.0.0.1',
        port: 514,
    }
}, function () {
    log.write("test", function () {
        log.write("test 2", function () {
            log.end();
        });
    });
});
```

I get this error:

```
$ node test.js

dgram.js:420
    throw new Error('Not running'); // error message from dgram_legacy.js
          ^
Error: Not running
    at Socket._healthCheck (dgram.js:420:11)
    at Socket.send (dgram.js:272:8)
    at UdpStream._write (/home/.../node_modules/syslog2/node_modules/udp-streams2/index.js:135:17)
    at doWrite (_stream_writable.js:223:10)
    at clearBuffer (_stream_writable.js:301:5)
    at onwrite (_stream_writable.js:259:7)
    at Object.WritableState.onwrite [as cb] (_stream_writable.js:97:5)
    at Object.afterSend [as oncomplete] (dgram.js:322:9)
```

I would expect to be able to write at least as fast as the callbacks are invoked.

**Comment by myndzi** [comment] 2015-02-05 03:00
That *is* pretty strange. "Not running"? Will check it out tomorrow.

**Comment by chazomaticus** [comment] 2015-02-05 03:08
Yeah, I looked briefly into it, but didn't see anything obvious.  Thanks for your help!

**Comment by myndzi** [comment] 2015-02-05 16:17
This turned out to be weirder than it seemed. It is actually a flaw in the udp-streams2 module that this module uses (I also wrote that one), but I was having trouble writing a test to reproduce. It turns out it only applies when you perform the shown steps on a stream that's *piped to* the udp stream. 

The underlying problem was async confusion: I had thought I should close the socket and call stream.end when done, but dgram.close is synchronous, so I just called that and the Writable's end method together. I needed to wait for the Writable stream's end method before closing the dgram socket.

**Closed** 2015-02-05 16:24 UTC
